Database migration
Herover/itu-devops-h pull request #87
Opened 2022-03-06 21:36 UTC by smilladion

Changes the database from SQLite to Postgres (running remotely on a DigitalOcean droplet).

2022-03-14 14:15 UTC, erentomurcuk approved these changes
Looks good! Checked syntax online as well, I was wondering if "user" was necessary instead of user.

2022-03-14 22:22 UTC, Herover requested changes
Quick review done without running the code :slightly_smiling_face:

2022-03-14 22:22 UTC, Herover commented on minitwit/README.md
> +* PostgreSQL as a remote database: https://mvnrepository.com/artifact/org.postgresql/postgresql
Maybe a link to PostgreSQLs webpage/docs would be appropriate as well if we are adding maven link

2022-03-14 22:22 UTC, Herover commented on minitwit/src/main/java/SqlDatabase.java
> +                "minitwituser", password
Can we also make the connection string and username environment variables? Makes it easier to switch out DB in case IP changes later.

2022-03-15 19:28 UTC, Herover commented on minitwit/src/main/java/SqlDatabase.java
> +                "minitwituser", password
Not sure, maybe nice to have the option later :)

2022-03-22 18:41 UTC, Herover approved these changes

2022-03-27 15:38 UTC, closed without merging